### ISSUE TITLE
Multiple transformations

### ISSUE THREAD

**Issue by dmi3kno** [coolbutuseless/minisvg#7]
I am looking at the [Transformations vignette](https://coolbutuseless.github.io/package/minisvg/articles/transformations.html) and I don't actually see multiple transformations applied, as the code suggests:
```r
heart_shadow <- stag$g(
  fill = 'grey',
  svg_prop$transform$rotate(-10, 50, 100),
  svg_prop$transform$translate(-36, 45.5),
  svg_prop$transform$skewX(40),
  svg_prop$transform$scale(1, 0.5),
  heart_shape
)
```
This should have translated to
```svg
  <g fill="grey" transform="rotate(-10 50 100) translate(-36 45.5) skewX(40) scale(1 0.5)">
```
![heart_3](https://user-images.githubusercontent.com/13419011/75269290-f6107100-57f8-11ea-89ba-a3dcc7b2f001.png)

While it only shows
```svg
  <g fill="grey" transform="scale(1 0.5)">
```
![heart_1](https://user-images.githubusercontent.com/13419011/75269435-2bb55a00-57f9-11ea-9001-e18786c14dcf.png)

It is actually pretty useful feature to be able to combine transforms and I would like to use it in other stags as well, such as in `$use`

**Comment by coolbutuseless** [comment]
Definite bug.

This used to work as documented.  Will investigate.
